import "./globals.css";
import { Suspense } from "react";
import Loading from "./loading";

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className="h-screen w-screen bg-stone-300 overflow-hidden">
        <Suspense
          fallback={
            <h1 className="text-center text-white bg-black text-9xl">
              loading..
            </h1>
          }
        >
          {children}
        </Suspense>
      </body>
    </html>
  );
}
